import { jsPDF } from "jspdf";
import { GRID_FACTS } from "../data/knowledge";

function gridFamily(gridSize) {
  if (!gridSize) return null;
  if (gridSize === "XS") return "XS";
  const m = gridSize.match(/^(6-Grid|10-Grid|20-Grid)/);
  return m ? m[1] : null;
}

// Generates and downloads a one-page config summary + spec sheet for the
// current recommendation — the client-side equivalent of "Save as PDF".
// `rec` is a computeRecommendation() snapshot, `state` the live app state,
// `t` the active translator.
export function downloadConfigPdf(rec, state, t) {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const marginX = 56;
  const labelX = marginX;
  const valueX = marginX + 160;
  let y = 60;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(227, 5, 18);
  doc.text("RATIONAL", marginX, y);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(90, 90, 90);
  doc.text(t("Your configuration"), marginX, y + 18);

  y += 56;
  doc.setDrawColor(220, 220, 220);
  doc.line(marginX, y, 556, y);
  y += 30;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.setTextColor(20, 20, 20);
  doc.text(`${t(rec.line)}, ${rec.gridSize ? t(rec.gridSize) : "—"}`, marginX, y);
  y += 30;

  const powerLabel = state.answers.power === "gas" ? t("gas") : state.answers.power === "electric" ? t("electric") : t("power TBD");
  const hoodLabel = rec.hood ? t(rec.hood) : "—";
  const standLabel = rec.stand ? t(rec.stand) : "—";
  const rackLabel = rec.rack ? t(rec.rack) : "—";
  const accessoriesLabel = state.accessories.length ? state.accessories.map((a) => t(a.label)).join(", ") : "—";

  const configRows = [
    [t("Model:"), rec.gridSize ? t(rec.gridSize) : "—"],
    [t("Power:"), powerLabel],
    [t("Hood:"), hoodLabel],
    [t("Stand:"), standLabel],
    [t("Rack:"), rackLabel],
    [t("Accessories:"), accessoriesLabel],
  ];

  doc.setFontSize(11);
  configRows.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(60, 60, 60);
    doc.text(label, labelX, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(20, 20, 20);
    doc.text(doc.splitTextToSize(String(value), 340), valueX, y);
    y += 20;
  });

  y += 20;
  const family = gridFamily(rec.gridSize);
  const facts = family ? GRID_FACTS[family] : null;
  if (facts) {
    doc.setDrawColor(220, 220, 220);
    doc.line(marginX, y, 556, y);
    y += 26;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(20, 20, 20);
    doc.text(t("Technical specifications"), marginX, y);
    y += 22;

    const specRows = [
      [t("Dimensions (W×D×H):"), facts.dims],
      [t("Weight:"), facts.weight],
      [t("Connected load:"), facts.power],
      [t("Pan capacity:"), facts.pans],
    ];
    doc.setFontSize(11);
    specRows.forEach(([label, value]) => {
      doc.setFont("helvetica", "bold");
      doc.setTextColor(60, 60, 60);
      doc.text(label, labelX, y);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(20, 20, 20);
      doc.text(String(value), valueX, y);
      y += 20;
    });
  }

  y += 24;
  doc.setDrawColor(220, 220, 220);
  doc.line(marginX, y, 556, y);
  y += 24;
  doc.setFontSize(9);
  doc.setTextColor(130, 130, 130);
  doc.setFont("helvetica", "normal");
  const footer = t(
    "Generated by the RATIONAL guided-selling demo. Dimensions, weight, and power figures are sourced from RATIONAL's published datasheets. Final pricing, lead time, and installation details are confirmed by your RATIONAL advisor."
  );
  doc.text(doc.splitTextToSize(footer, 500), marginX, y);

  const fileSafeSize = (rec.gridSize || "config").replace(/[^\w-]+/g, "-");
  doc.save(`RATIONAL-${fileSafeSize}.pdf`);
}
